package dev.praajeet.optimus

import io.swagger.v3.oas.annotations.OpenAPIDefinition
import io.swagger.v3.oas.annotations.info.Contact
import io.swagger.v3.oas.annotations.info.Info
import io.swagger.v3.oas.annotations.info.License
import io.swagger.v3.oas.annotations.servers.Server
import io.swagger.v3.oas.annotations.tags.Tag
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
@OpenAPIDefinition(
    info = Info(
        title = "Optimus Prime API",
        version = "1.0",
        description = "API for performing various Prime number related operations in a quick and efficient manner. "
                + "Prime numbers are numbers greater than `1` that have no positive divisors other than `1` and themselves. "
                + "They have numerous applications in many fields of mathematics and computer science. "
                + "The name <b>Optimus Prime</b> was inspired by the Transformers character.<br><br>"
                + "<b>IMPORTANT:</b> The API response are predominantly based on 64 bit integer `(2^63 - 1)`, But javascript Number type is precise upto `2^53 - 1` alone."
                + "Therefore this Documentation page generated by Swagger may display inaccurate numbers even though the JSON response is accurate.",
        contact = Contact(name = "Praajeet", email = "mr@praajeet.dev"),
        license = License(name = "GPL 3.0", url = "https://www.gnu.org/licenses/gpl-3.0.en.html")
    ),
    servers = [
        Server(url = "http://localhost:8080", description = "Local Development Server"),
        Server(url = "https://optimus.praajeet.dev", description = "Production Server")
    ],
    tags = [
        Tag(name = "Basic Prime Operations"),
        Tag(name = "Number Theory Operations"),
        Tag(name = "Special Prime Operations"),
    ]
)
class PrimeApplication

fun main(args: Array<String>) {
    runApplication<PrimeApplication>(*args)
}
